### PR TITLE
Added support for adjusting the number of rows of a section

### PR DESCRIPTION
**Pull request by gfzabarino**
Added support for adjusting the number of rows of a section and optionally reloading the affected section in the table view.

### CODE REVIEW

**Comment by jhersh** [comment]
Interesting! Thanks.

This is meant to be used with an `SSSection` that contains placeholder objects, correct?

If so, my first thought is that all of the `adjustToNumberOfItems:` logic should be contained within `SSSectionedDataSource`, since you almost never want to mutate a section's items without also allowing the data source to insert/delete/reload as appropriate, otherwise the table or collection view will become inconsistent with its data source.

Can you give me an example of a time you would use this method and NOT also reload the table? That also seems like a recipe for an inconsistent table. Also, this change is specific to tables; ideally we would use the base data source's insert/delete/reload methods, which handle both tables and collection views and use the proper row animation.

**Comment by gfzabarino** [comment]
No problem.

I just moved the `adjustToNumberOfItems:` logic to `SSSectionedDataSource`, what you say makes total sense. And correct, this is for `SSSection` that contains placeholder objects.

As an example, I'm using a `NSFetchedResultsController` to populate just a given section of a table view. Whatever updates it reports, I need to use the `reloadSections:withRowAnimation:` since the other parts of the table view don't change. Using the other per-cell methods doesn't make it look good on a certain view controller transition I make, so I need to call that method.

**Comment by jhersh** [comment]
Hmm, I'm not sure I follow your example. You have a table with several sections, one section of which is backed by an `NSFetchedResultsController`. You would use this new method to update the items in a different section, but again, when would you use this new method without also reloading that section? 

Also, why not insert or delete rows as appropriate instead of reloading the full section?

**Comment by gfzabarino** [comment]
> Hmm, I'm not sure I follow your example. You have a table with several sections, one section of which is backed by an NSFetchedResultsController.

Yes, that's right.

> You would use this new method to update the items in a different section,

No, I would use this method to update the number of rows of the section that is displaying the `NSFetchedResultsController` results. Maybe I'm wrong, and you can change the number of rows that this framework returns for a given section in a different way?

> but again, when would you use this new method without also reloading that section?

This is method does reload the section (model) and calls the `reloadSectionsAtIndexes:` method of `SSBaseDataSource`.

> Also, why not insert or delete rows as appropriate instead of reloading the full section?

Because of an artifact that happens when the effect is displayed. It's not such a big deal, but I do rather call `reloadSectionsAtIndexes:` instead. Besides, I think this is a valid use of what I would do if I would not be using SSDataSources. Maybe I'm just wrong and there's some concept I'm missing.

Thanks for the follow-up on this.

**Comment by jhersh** [comment]
> No, I would use this method to update the number of rows of the section that is displaying the NSFetchedResultsController results. 

So you wouldn't use `SSCoreDataSource` because you have multiple sections in the table, not all of which are backed by core data?

Also, it sounds like the items in your data source for the core data section are just placeholder objects, not your `NSManagedObject` subclass? If so, I think I understand your use case.

>> but again, when would you use this new method without also reloading that section?

> This method does reload the section (model) and calls the reloadSectionsAtIndexes: method of SSBaseDataSource.

Understood, I'm just trying to understand the BOOL `reloadSection` parameter in this new method. When would you ever call that with `reloadSection` == `NO` ? If you don't reload the section, surely the table and data source will become inconsistent?

**Comment by gfzabarino** [comment]
> So you wouldn't use SSCoreDataSource because you have multiple sections in the table, not all of which are backed by core data?

Yup, that's right. I have some sections with static cells, and this one section backed up by `NSFechedResultsController`. `SSCoreDataSource` is supposed to work with the entire table view and it uses the sections provided by `NSFechedResultsController`, right?

> Also, it sounds like the items in your data source for the core data section are just placeholder objects, not your NSManagedObject subclass? If so, I think I understand your use case.

Yup, that's it. I was actually trying to mimic the behavior of the `SSSection` `sectionWithNumberOfItems:` method.

> Understood, I'm just trying to understand the BOOL reloadSection parameter in this new method. When would you ever call that with reloadSection == NO ? If you don't reload the section, surely the table and data source will become inconsistent?

You're right about this. Maybe a user would want to make a call to `reloadSectionsAtIndexes:` after calling this method passing multiple section identifiers. But I guess that's not such a common case. Maybe it would be better to remove the `reloadSection` parameter. What do you think?

**Comment by jhersh** [comment]
> `SSCoreDataSource` is supposed to work with the entire table view and it uses the sections provided by NSFechedResultsController, right?

Yup, that's the standard implementation. I've also seen it subclassed to customize that behavior.

> Maybe it would be better to remove the `reloadSection` parameter.

:+1:

**Comment by jhersh** [comment]
Thanks! I'll be tweaking this a little for style, plus we'll probably need to override this in `SSExpandingDataSource` to work properly for collapsed sections.

**Comment by jhersh** [comment]
I added some docs, tests, and support for `shouldRemoveEmptySections`. Thanks for this, @gfzabarino!

**Comment by gfzabarino** [comment]
You're welcome @jhersh! This framework rocks!

**Pull request merged**
